### ISSUE TITLE
v0.4.5 image_model_wrapper bug: torch import optional, but still referenced in global scope.

### ISSUE THREAD

**Issue by MaurisLucis** [microsoft/ml-wrappers#99]
https://github.com/microsoft/ml-wrappers/blob/b090ac13450b23894cdcc66559422b0e60b5a397/python/ml_wrappers/model/image_model_wrapper.py#L404

**Comment by imatiach-msft** [comment]
fixed with PR:
https://github.com/microsoft/ml-wrappers/pull/98
and 0.4.6 release to pypi of ml-wrappers:
https://pypi.org/project/ml-wrappers/#history
